MERGE INTO "DBIMART_DEV"."CUSTOMER_REPORTING"."REFUNDS" t
USING "DBIMART_DEV"."CUSTOMER_REPORTING"."REFUNDS_STAG" s
ON s.order_id = t.order_id AND s.sku = t.sku and t.companyNumber = s.companyNumber
and s.size = t.size and s.refundId = t.refundId and s.refundNum =t.refundNum
WHEN MATCHED THEN UPDATE SET
t.refund_header_date = s.refund_header_date ,
t.refund_status = s.refund_status ,
t.refund_createdBy = s.refund_createdBy,
t.refund_userId = s.refund_userId,
t.source = s.source ,
t.quantity = s.quantity ,
t.name = s.name ,
t.color = s.color ,
t.image = s.image,
t.brand = s.brand ,
t.category = s.category ,
t.description = s.description ,
t.isCollectUpFront = s.isCollectUpFront ,
t.backorderFlag = s.backorderFlag ,
t.launchSkuFlag = s.launchSkuFlag ,
t.taxCode = s.taxCode ,
t.productDesignator = s.productDesignator ,
t.productNumber = s.productNumber ,
t.productType = s.productType ,
t.cegrRefId = s.cegrRefId,
t.originalRetailPrice = s.originalRetailPrice ,
t.originalUnitPrice = s.originalUnitPrice ,
t.originalUnitDiscountAmount = s.originalUnitDiscountAmount ,
t.lineRefundSubTotal = s.lineRefundSubTotal ,
t.taxAmount = s.taxAmount ,
t.shippingAmount = s.shippingAmount ,
t.shippingTaxAmount = s.shippingTaxAmount ,
t.inboundShippingAmount = s.inboundShippingAmount ,
t.totalAmount = s.totalAmount ,
t.returnExpected = s.returnExpected ,
t.returned = s.returned ,
t.returnNumbers = s.returnNumbers,
t.quantityReturned = s.quantityReturned ,
t.returnDate = s.returnDate ,
t.reasonCode = s.reasonCode ,
t.ih_inboundShippingAmount = s.ih_inboundShippingAmount ,
t.ih_lineRefundSubTotal = s.ih_lineRefundSubTotal ,
t.ih_originalRetailPrice = s.ih_originalRetailPrice ,
t.ih_originalUnitDiscountAmount = s.ih_originalUnitDiscountAmount ,
t.ih_originalUnitPrice = s.ih_originalUnitPrice ,
t.ih_shippingAmount = s.ih_shippingAmount ,
t.ih_shippingTaxAmount = s.ih_shippingTaxAmount ,
t.ih_taxAmount = s.ih_taxAmount ,
t.ih_totalAmount = s.ih_totalAmount ,
t.refundMethods = s.refundMethods,
t.paymentsInfo = s.paymentsInfo,
t.refund_notes = s.refund_notes,
t.refunds_statusHistory = s.refunds_statusHistory,
t.load_time_kafka = s.load_time_kafka ,
t.postedAt = s.postedAt ,
t.updated_datetime = s.load_time_adls
WHEN NOT MATCHED THEN INSERT (
ORDER_ID,t.ORDER_DATETIME,t.REFUNDID,t.COMPANYNUMBER,t.REFUND_HEADER_DATE,t.REFUND_STATUS,t.REFUND_CREATEDBY,t.REFUND_USERID,t.SOURCE,t.REFUNDNUM,t.QUANTITY,t.NAME,t.SKU,t.SIZE,t.COLOR,t.IMAGE,t.BRAND,t.CATEGORY,t.DESCRIPTION,t.ISCOLLECTUPFRONT,t.BACKORDERFLAG,t.LAUNCHSKUFLAG,t.TAXCODE,t.PRODUCTDESIGNATOR,t.PRODUCTNUMBER,t.PRODUCTTYPE,t.CEGRREFID,t.ORIGINALRETAILPRICE,t.ORIGINALUNITPRICE,t.ORIGINALUNITDISCOUNTAMOUNT,t.LINEREFUNDSUBTOTAL,t.TAXAMOUNT,t.SHIPPINGAMOUNT,t.SHIPPINGTAXAMOUNT,t.INBOUNDSHIPPINGAMOUNT,t.TOTALAMOUNT,t.RETURNEXPECTED,t.RETURNED,t.RETURNNUMBERS,t.QUANTITYRETURNED,t.RETURNDATE,t.REASONCODE,t.IH_INBOUNDSHIPPINGAMOUNT,t.IH_LINEREFUNDSUBTOTAL,t.IH_ORIGINALRETAILPRICE,t.IH_ORIGINALUNITDISCOUNTAMOUNT,t.IH_ORIGINALUNITPRICE,t.IH_SHIPPINGAMOUNT,t.IH_SHIPPINGTAXAMOUNT,t.IH_TAXAMOUNT,t.IH_TOTALAMOUNT,t.REFUNDMETHODS,t.PAYMENTSINFO,t.REFUND_NOTES,t.REFUNDS_STATUSHISTORY,t.LOAD_TIME_KAFKA,t.LOAD_TIME_ADLS,t.ORDER_DATE,t.POSTEDAT,t.POSTEDBY,t.UPDATED_DATETIME)
values (ORDER_ID,s.ORDER_DATETIME,s.REFUNDID,s.COMPANYNUMBER,s.REFUND_HEADER_DATE,s.REFUND_STATUS,s.REFUND_CREATEDBY,s.REFUND_USERID,s.SOURCE,s.REFUNDNUM,s.QUANTITY,s.NAME,s.SKU,s.SIZE,s.COLOR,s.IMAGE,s.BRAND,s.CATEGORY,s.DESCRIPTION,s.ISCOLLECTUPFRONT,s.BACKORDERFLAG,s.LAUNCHSKUFLAG,s.TAXCODE,s.PRODUCTDESIGNATOR,s.PRODUCTNUMBER,s.PRODUCTTYPE,s.CEGRREFID,s.ORIGINALRETAILPRICE,s.ORIGINALUNITPRICE,s.ORIGINALUNITDISCOUNTAMOUNT,s.LINEREFUNDSUBTOTAL,s.TAXAMOUNT,s.SHIPPINGAMOUNT,s.SHIPPINGTAXAMOUNT,s.INBOUNDSHIPPINGAMOUNT,s.TOTALAMOUNT,s.RETURNEXPECTED,s.RETURNED,s.RETURNNUMBERS,s.QUANTITYRETURNED,s.RETURNDATE,s.REASONCODE,s.IH_INBOUNDSHIPPINGAMOUNT,s.IH_LINEREFUNDSUBTOTAL,s.IH_ORIGINALRETAILPRICE,s.IH_ORIGINALUNITDISCOUNTAMOUNT,s.IH_ORIGINALUNITPRICE,s.IH_SHIPPINGAMOUNT,s.IH_SHIPPINGTAXAMOUNT,s.IH_TAXAMOUNT,s.IH_TOTALAMOUNT,s.REFUNDMETHODS,s.PAYMENTSINFO,s.REFUND_NOTES,s.REFUNDS_STATUSHISTORY,s.LOAD_TIME_KAFKA,s.LOAD_TIME_ADLS,s.ORDER_DATE,s.POSTEDAT,s.POSTEDBY,s.UPDATED_DATETIME)