MERGE INTO "DBIMART_DEV"."CUSTOMER_REPORTING"."ORDERS" t
USING (select * from
(select * ,
row_number() over (partition by company_number,order_id,order_lineNumber,fullfillment_type order by POSTEDAT desc) as rnk
from "DBIMART_DEV"."CUSTOMER_REPORTING"."ORDERS_STAG") a where rnk =1) s
ON s.order_id = t.order_id AND s.order_lineNumber = t.order_lineNumber and t.company_number = s.company_number and t.fullfillment_type = s.fullfillment_type
WHEN MATCHED THEN UPDATE SET
t.first_name = s.first_name,
t.last_name = s.last_name,
t.billing_address_line1 = s.billing_address_line1,
t.billing_address_line2 = s.billing_address_line2,
t.billing_first_name = s.billing_first_name,
t.billing_last_name = s.billing_last_name,
t.billing_phoneNumber = s.billing_phoneNumber,
t.shipping_phoneNumber = s.shipping_phoneNumber,
t.store_fulfillment_deliveryInstructions = s.store_fulfillment_deliveryInstructions,
t.store_fulfillment_deliverycustomerphone = s.store_fulfillment_deliverycustomerphone,
t.user_ip_address = s.user_ip_address,
t.shipping_addressline1 = s.shipping_addressline1,
t.shipping_addressline2 = s.shipping_addressline2,
t.shipping_first_name = s.shipping_first_name,
t.shipping_last_name = s.shipping_last_name,
t.order_phoneNumber = s.order_phoneNumber,
t.store_fulfillment_pickupPersonMobile = s.store_fulfillment_pickupPersonMobile,
t.order_status=s.order_status,
t.cancel_code=s.cancel_code,
t.cancelReason = s.cancelReason,
t.free_shipping=s.free_shipping,
t.order_salecode = s.order_salecode,
t.order_priceOverrideReason = s.order_priceOverrideReason,
t.order_currency=s.order_currency,
t.order_discountAmount=s.order_discountAmount,
t.order_discounted_totalAmount=s.order_discounted_totalAmount,
t.order_original_retailPrice=s.order_original_retailPrice,
t.order_shippingAmount=s.order_shippingAmount,
t.order_shippingTaxAmount = s.order_shippingTaxAmount,
t.order_subTotalAmount=s.order_subTotalAmount,
t.order_giftBoxAmount = s.order_giftBoxAmount,
t.order_giftBoxTaxAmount = s.order_giftBoxTaxAmount,
t.order_taxAmount=s.order_taxAmount,
t.order_totalAmount=s.order_totalAmount,
t.order_unitPrice=s.order_unitPrice,
t.order_giftCardNum = s.order_giftCardNum,
t.order_inventoryLocation = s.order_inventoryLocation,
t.order_backorderFlag=s.order_backorderFlag,
t.order_product_brand=s.order_product_brand,
t.order_product_category=s.order_product_category,
t.order_product_color=s.order_product_color,
t.order_product_description=s.order_product_description,
t.order_product_isCollectUpFront=s.order_product_isCollectUpFront,
t.order_product_launch_SkuFlag=s.order_product_launch_SkuFlag,
t.order_product_name=s.order_product_name,
t.order_product_designator=s.order_product_designator,
t.order_product_number=s.order_product_number,
t.order_product_type=s.order_product_type,
t.order_product_size=s.order_product_size,
t.order_product_sku=s.order_product_sku,
t.order_product_taxCode=s.order_product_taxCode,
t.order_quantity=s.order_quantity,
t.order_shipMethod=s.order_shipMethod,
t.order_taxCode=s.order_taxCode,
t.store_fulfillment_shipMethod = s.store_fulfillment_shipMethod,
t.store_fulfillment_storeNumber = s.store_fulfillment_storeNumber,
t.store_fulfillment_fulfillmentType = s.store_fulfillment_fulfillmentType,
t.store_fulfillment_pickupPersonEmail = s.store_fulfillment_pickupPersonEmail,
t.store_fulfillment_storeCostOfGoods = s.store_fulfillment_storeCostOfGoods,
t.store_fulfillment_deliveryEstimateID = s.store_fulfillment_deliveryEstimateID,
t.exchangeOrder_flag = s.exchangeOrder_flag,
t.billing_city = s.billing_city,
t.billing_country = s.billing_country,
t.billing_email = s.billing_email,
t.billing_postal_code = s.billing_postal_code,
t.billing_postal_state = s.billing_postal_state,
t.order_giftbox_flag=s.order_giftbox_flag,
t.order_giftorder_flag=s.order_giftorder_flag,
t.order_langID=s.order_langID,
t.coupons=s.coupons,
t.channel=s.channel  ,
t.order_datetime=s.order_datetime,
t.baseShippingCharged = s.baseShippingCharged,
t.shippableConsignmentCount = s.shippableConsignmentCount,
t.referralSite = s.referralSite,
t.oh_base_shipping_amount=s.oh_base_shipping_amount,
t.oh_currency=s.oh_currency,
t.oh_couponamount = s.oh_couponamount,
t.oh_giftBoxAmount = s.oh_giftBoxAmount,
t.oh_giftBoxTaxAmount = s.oh_giftBoxTaxAmount,
t.oh_baseShippingTaxAmount = s.oh_baseShippingTaxAmount,
t.oh_settledAmount = s.oh_settledAmount,
t.oh_discounted_amount=s.oh_discounted_amount,
t.oh_discounted_total_amount=s.oh_discounted_total_amount,
t.oh_gateway=s.oh_gateway,
t.oh_shipping_amount=s.oh_shipping_amount,
t.oh_subTotal_amount=s.oh_subTotal_amount,
t.oh_tax_amount=s.oh_tax_amount,
t.oh_total_amount=s.oh_total_amount,
t.email= s.email,
t.user_id=s.user_id,
t.user_type=s.user_type,
t.order_affiliateIdTime = s.order_affiliateIdTime,
t.order_affiliate_id = s.order_affiliate_id,
t.order_flrequest_id = s.order_flrequest_id,
t.order_request_id=s.order_request_id,
t.order_request_date=s.order_request_date,
t.order_request_type=s.order_request_type,
t.rush_flag=s.rush_flag,
t.sales_personID=s.sales_personID,
t.ship_method=s.ship_method,
t.ship_method_desc=s.ship_method_desc,
t.vendorId=s.vendorId,
t.web_order_number=s.web_order_number,
t.migratedOrder = s.migratedOrder,
t.order_overrideReasonCd = s.order_overrideReasonCd,
t.order_source = s.order_source,
t.relatedordernumber_csa = s.relatedordernumber_csa,
t.controllerOrderNumber = s.controllerOrderNumber,
t.shipping_city=s.shipping_city,
t.shipping_country=s.shipping_country,
t.shipping_state=s.shipping_state,
t.shipping_postal_code=s.shipping_postal_code,
t.shipping_email = s.shipping_email,
t.csaAgentId = s.csaAgentId,
t.csaOrderNote = s.csaOrderNote,
t.order_division = s.order_division,
t.omsOrderId = s.omsOrderId,
t.postedAt=s.postedAt,
t.load_time_kafka=s.load_time_kafka,
t.order_date=s.order_date,
t.updated_datetime = s.load_time_adls,
t.controllerCustomerId = s.controllerCustomerId,
t.relateCustomerId = s.relateCustomerId,
t.flxId = s.flxId
WHEN NOT MATCHED THEN INSERT (t.ORDER_ID,t.COMPANY_NUMBER,t.ORDER_STATUS,t.CANCEL_CODE,t.CANCELREASON,t.FULLFILLMENT_TYPE,t.FREE_SHIPPING,
t.ORDER_LINENUMBER,t.ORDER_CURRENCY,t.ORDER_SALECODE,t.ORDER_PRICEOVERRIDEREASON,t.ORDER_DISCOUNTAMOUNT,t.ORDER_DISCOUNTED_TOTALAMOUNT,
t.ORDER_ORIGINAL_RETAILPRICE,t.ORDER_SHIPPINGAMOUNT,t.ORDER_SHIPPINGTAXAMOUNT,t.ORDER_SUBTOTALAMOUNT,t.ORDER_TAXAMOUNT,t.ORDER_GIFTBOXAMOUNT,
t.ORDER_GIFTBOXTAXAMOUNT,t.ORDER_TOTALAMOUNT,t.ORDER_UNITPRICE,t.ORDER_GIFTCARDNUM,t.ORDER_INVENTORYLOCATION,t.ORDER_PRODUCT_NAME,
t.ORDER_PRODUCT_IMAGE,t.ORDER_BACKORDERFLAG,t.ORDER_PRODUCT_BRAND,t.ORDER_PRODUCT_CATEGORY,t.ORDER_PRODUCT_COLOR,t.ORDER_PRODUCT_DESCRIPTION,
t.ORDER_PRODUCT_ISCOLLECTUPFRONT,t.ORDER_PRODUCT_LAUNCH_SKUFLAG,t.ORDER_PRODUCT_DESIGNATOR,t.ORDER_PRODUCT_NUMBER,t.ORDER_PRODUCT_TYPE,
t.ORDER_PRODUCT_SIZE,t.ORDER_PRODUCT_SKU,t.ORDER_PRODUCT_TAXCODE,t.ORDER_QUANTITY,t.ORDER_SHIPMETHOD,t.ORDER_TAXCODE,
t.STORE_FULFILLMENT_SHIPMETHOD,t.STORE_FULFILLMENT_STORENUMBER,t.STORE_FULFILLMENT_FULFILLMENTTYPE,t.STORE_FULFILLMENT_PICKUPPERSONEMAIL,
t.STORE_FULFILLMENT_PICKUPPERSONMOBILE,t.STORE_FULFILLMENT_STORECOSTOFGOODS,t.STORE_FULFILLMENT_DELIVERYESTIMATEID,
t.STORE_FULFILLMENT_DELIVERYINSTRUCTIONS,t.STORE_FULFILLMENT_DELIVERYCUSTOMERPHONE,t.EXCHANGEORDER_FLAG,t.BILLING_ADDRESS_LINE1,
t.BILLING_ADDRESS_LINE2,t.BILLING_CITY,t.BILLING_COUNTRY,t.BILLING_EMAIL,t.BILLING_FIRST_NAME,t.BILLING_LAST_NAME,
t.BILLING_POSTAL_CODE,t.BILLING_POSTAL_STATE,t.BILLING_PHONENUMBER,t.ORDER_GIFTBOX_FLAG,t.ORDER_GIFTORDER_FLAG,
t.ORDER_LANGID,t.COUPONS,t.CHANNEL,t.ORDER_DATETIME,t.BASESHIPPINGCHARGED,t.SHIPPABLECONSIGNMENTCOUNT,t.REFERRALSITE,
t.OH_BASE_SHIPPING_AMOUNT,t.OH_CURRENCY,t.OH_COUPONAMOUNT,t.OH_GIFTBOXAMOUNT,t.OH_GIFTBOXTAXAMOUNT,t.OH_BASESHIPPINGTAXAMOUNT,
t.OH_SETTLEDAMOUNT,t.OH_DISCOUNTED_AMOUNT,t.OH_DISCOUNTED_TOTAL_AMOUNT,t.OH_GATEWAY,t.OH_SHIPPING_AMOUNT,t.OH_SUBTOTAL_AMOUNT,
t.OH_TAX_AMOUNT,t.OH_TOTAL_AMOUNT,t.EMAIL,t.FIRST_NAME,t.LAST_NAME,t.USER_ID,t.USER_TYPE,t.CONTROLLERCUSTOMERID,t.RELATECUSTOMERID,
t.FLXID,t.ORDER_PHONENUMBER,t.ORDER_AFFILIATEIDTIME,t.ORDER_AFFILIATE_ID,t.ORDER_FLREQUEST_ID,t.ORDER_REQUEST_ID,t.ORDER_REQUEST_DATE,
t.ORDER_REQUEST_TYPE,t.ORDER_REQUESTER,t.RUSH_FLAG,t.SALES_PERSONID,t.SHIP_METHOD,t.SHIP_METHOD_DESC,t.USER_IP_ADDRESS,t.VENDORID,
t.WEB_ORDER_NUMBER,t.MIGRATEDORDER,t.ORDER_OVERRIDEREASONCD,t.ORDER_SOURCE,t.RELATEDORDERNUMBER_CSA,t.CONTROLLERORDERNUMBER,
t.SHIPPING_ADDRESSLINE1,t.SHIPPING_ADDRESSLINE2,t.SHIPPING_CITY,t.SHIPPING_COUNTRY,t.SHIPPING_STATE,t.SHIPPING_POSTAL_CODE,
t.SHIPPING_EMAIL,t.SHIPPING_FIRST_NAME,t.SHIPPING_LAST_NAME,t.SHIPPING_PHONENUMBER,t.CSAAGENTID,t.CSAORDERNOTE,t.ORDER_DIVISION,
t.OMSORDERID,t.POSTEDBY,t.POSTEDAT,t.LOAD_TIME_KAFKA,t.ORDER_DATE,t.LOAD_TIME_ADLS,t.COGS,t.UPDATED_DATETIME)
values (s.ORDER_ID,s.COMPANY_NUMBER,s.ORDER_STATUS,s.CANCEL_CODE,s.CANCELREASON,s.FULLFILLMENT_TYPE,s.FREE_SHIPPING,
s.ORDER_LINENUMBER,s.ORDER_CURRENCY,s.ORDER_SALECODE,s.ORDER_PRICEOVERRIDEREASON,s.ORDER_DISCOUNTAMOUNT,s.ORDER_DISCOUNTED_TOTALAMOUNT,
s.ORDER_ORIGINAL_RETAILPRICE,s.ORDER_SHIPPINGAMOUNT,s.ORDER_SHIPPINGTAXAMOUNT,s.ORDER_SUBTOTALAMOUNT,s.ORDER_TAXAMOUNT,s.ORDER_GIFTBOXAMOUNT,
s.ORDER_GIFTBOXTAXAMOUNT,s.ORDER_TOTALAMOUNT,s.ORDER_UNITPRICE,s.ORDER_GIFTCARDNUM,s.ORDER_INVENTORYLOCATION,s.ORDER_PRODUCT_NAME,
s.ORDER_PRODUCT_IMAGE,s.ORDER_BACKORDERFLAG,s.ORDER_PRODUCT_BRAND,s.ORDER_PRODUCT_CATEGORY,s.ORDER_PRODUCT_COLOR,s.ORDER_PRODUCT_DESCRIPTION,
s.ORDER_PRODUCT_ISCOLLECTUPFRONT,s.ORDER_PRODUCT_LAUNCH_SKUFLAG,s.ORDER_PRODUCT_DESIGNATOR,s.ORDER_PRODUCT_NUMBER,s.ORDER_PRODUCT_TYPE,
s.ORDER_PRODUCT_SIZE,s.ORDER_PRODUCT_SKU,s.ORDER_PRODUCT_TAXCODE,s.ORDER_QUANTITY,s.ORDER_SHIPMETHOD,s.ORDER_TAXCODE,
s.STORE_FULFILLMENT_SHIPMETHOD,s.STORE_FULFILLMENT_STORENUMBER,s.STORE_FULFILLMENT_FULFILLMENTTYPE,s.STORE_FULFILLMENT_PICKUPPERSONEMAIL,
s.STORE_FULFILLMENT_PICKUPPERSONMOBILE,s.STORE_FULFILLMENT_STORECOSTOFGOODS,s.STORE_FULFILLMENT_DELIVERYESTIMATEID,
s.STORE_FULFILLMENT_DELIVERYINSTRUCTIONS,s.STORE_FULFILLMENT_DELIVERYCUSTOMERPHONE,s.EXCHANGEORDER_FLAG,s.BILLING_ADDRESS_LINE1,
s.BILLING_ADDRESS_LINE2,s.BILLING_CITY,s.BILLING_COUNTRY,s.BILLING_EMAIL,s.BILLING_FIRST_NAME,s.BILLING_LAST_NAME,
s.BILLING_POSTAL_CODE,s.BILLING_POSTAL_STATE,s.BILLING_PHONENUMBER,s.ORDER_GIFTBOX_FLAG,s.ORDER_GIFTORDER_FLAG,
s.ORDER_LANGID,s.COUPONS,s.CHANNEL,s.ORDER_DATETIME,s.BASESHIPPINGCHARGED,s.SHIPPABLECONSIGNMENTCOUNT,s.REFERRALSITE,
s.OH_BASE_SHIPPING_AMOUNT,s.OH_CURRENCY,s.OH_COUPONAMOUNT,s.OH_GIFTBOXAMOUNT,s.OH_GIFTBOXTAXAMOUNT,s.OH_BASESHIPPINGTAXAMOUNT,
s.OH_SETTLEDAMOUNT,s.OH_DISCOUNTED_AMOUNT,s.OH_DISCOUNTED_TOTAL_AMOUNT,s.OH_GATEWAY,s.OH_SHIPPING_AMOUNT,s.OH_SUBTOTAL_AMOUNT,
s.OH_TAX_AMOUNT,s.OH_TOTAL_AMOUNT,s.EMAIL,s.FIRST_NAME,s.LAST_NAME,s.USER_ID,s.USER_TYPE,s.CONTROLLERCUSTOMERID,s.RELATECUSTOMERID,
s.FLXID,s.ORDER_PHONENUMBER,s.ORDER_AFFILIATEIDTIME,s.ORDER_AFFILIATE_ID,s.ORDER_FLREQUEST_ID,s.ORDER_REQUEST_ID,s.ORDER_REQUEST_DATE,
s.ORDER_REQUEST_TYPE,s.ORDER_REQUESTER,s.RUSH_FLAG,s.SALES_PERSONID,s.SHIP_METHOD,s.SHIP_METHOD_DESC,s.USER_IP_ADDRESS,s.VENDORID,
s.WEB_ORDER_NUMBER,s.MIGRATEDORDER,s.ORDER_OVERRIDEREASONCD,s.ORDER_SOURCE,s.RELATEDORDERNUMBER_CSA,s.CONTROLLERORDERNUMBER,
s.SHIPPING_ADDRESSLINE1,s.SHIPPING_ADDRESSLINE2,s.SHIPPING_CITY,s.SHIPPING_COUNTRY,s.SHIPPING_STATE,s.SHIPPING_POSTAL_CODE,
s.SHIPPING_EMAIL,s.SHIPPING_FIRST_NAME,s.SHIPPING_LAST_NAME,s.SHIPPING_PHONENUMBER,s.CSAAGENTID,s.CSAORDERNOTE,s.ORDER_DIVISION,
s.OMSORDERID,s.POSTEDBY,s.POSTEDAT,s.LOAD_TIME_KAFKA,s.ORDER_DATE,s.LOAD_TIME_ADLS,s.COGS,s.LOAD_TIME_ADLS
)